{{ if .Values.deafultImagePullSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerhub-token
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-dockerhub-token
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ `{{ .username }}` }}",
                "password": "{{ `{{ .password }}` }}"
              }
            }
          }
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: dockerhub-token
      property: password
  - secretKey: username
    remoteRef:
      key: dockerhub-token
      property: username
{{ end }}
